[project]
name = "videos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "janim[gui]>=3.10.2",
    "manim-devanagari>=0.2.2",
]
