[project]
name = "videos"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "indic-transliteration>=2.3.75",
  "janim[gui]>=4.0.0a7",
  "manim-devanagari>=0.2.2",
  "parsimonious>=0.11.0",
]
